name: Nightly install package test
on:
  push:
    paths:
      - .github/workflows/install_package.yml
  schedule:
    - cron: '15 2 * * *'
jobs:

  Verify_Linux:
    name: Verify packages Linux
    strategy:
      # When true GitHub will cancel all in-progress and queued jobs in the matrix if any job in the matrix fails.
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10", "3.11"]
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    outputs:
      PATHWAY_VER_Linux: ${{ steps.package_version_linux.outputs.PATHWAY_VER_Linux }}
    steps:
      - name: Install_verify
        id: package_version_linux
        run: |
          set -ex
          ENV_NAME="testenv_"${{ matrix.python-version }}""
          rm -rf $ENV_NAME
          python -m venv ${ENV_NAME}
          source ${ENV_NAME}/bin/activate
          pip install --prefer-binary -U --extra-index-url https://packages.pathway.com/966431ef6ba pathway
          PATHWAY_VER=$(python -c 'import pathway; print(pathway.__version__)')
          echo "PATHWAY_VER_Linux=$PATHWAY_VER" >> $GITHUB_OUTPUT

  List_tested_version:
    name: list tested version
    needs: 
      - Verify_Linux
    strategy:
      # When true GitHub will cancel all in-progress and queued jobs in the matrix if any job in the matrix fails.
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - name: Installed Pathway version
        run: |
          echo "Linux: ${{ needs.Verify_Linux.outputs.PATHWAY_VER_Linux }}"

  Notify_on_failure:
    needs:
      - Verify_Linux
      - List_tested_version
    if: failure()
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: ${{ secrets.CHANNEL }} ## #github-action channel
          # For posting a simple plain text message
          payload: |
            {
              "text": "Nightly ${{ needs.Verify_Linux.outputs.PATHWAY_VER_Linux}} test failure :manul:\nRun: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Nightly ${{ needs.Verify_Linux.outputs.PATHWAY_VER_Linux }} test failure :manul:\nRun: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}